url: https://dbacca.github.io
baseurl: /dbacca.github.io

# Site settings
title: Drew Since Web Developer
email: Drew.Since@gmail.com
description: "This is the site that will make you want to hire Drew as your new Dev!"


# Team names, titles and socials links
people:
- name: Drew Since
  pic: 2
  position: Web Developer
  social:
    - title: twitter
      url: https://twitter.com/drewsincetravel
    - title: facebook
      url: https://www.facebook.com/drew.sincebaugh
    - title: github
      url: http://github.com/dbacca
    - title: instagram
      url: http://instagram.com/drewsince



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/drewsincetravel
  - title: facebook
    url: https://www.facebook.com/drew.sincebaugh

  - title: github
    url: http://github.com/dbacca

# Postal address (add as many lines as necessary)
address:
  - line: Chaing Mai, Thailand
  - line: Soon to be Seattle, Washington

# Build settings
markdown: kramdown
permalink: pretty
